export const NIFTY_200 = [
  { key: "DIVISLAB", text: "Divis Laboratories Ltd." },
  { key: "JINDALSTEL", text: "Jindal Steel & Power Ltd." },
  { key: "ENDURANCE", text: "Endurance Technologies Ltd." },
  { key: "PGHH", text: "Procter & Gamble Hygiene & Health Care Ltd." },
  { key: "GMRINFRA", text: "GMR Infrastructure Ltd." },
  { key: "UNIONBANK", text: "Union Bank of India" },
  { key: "RAMCOCEM", text: "The Ramco Cements Ltd." },
  { key: "GAIL", text: "GAIL (India) Ltd." },
  { key: "ICICIBANK", text: "ICICI Bank Ltd." },
  { key: "ICICIGI", text: "ICICI Lombard General Insurance Company Ltd." },
  { key: "LTFH", text: "L&T Finance Holdings Ltd." },
  { key: "HINDUNILVR", text: "Hindustan Unilever Ltd." },
  { key: "SBIN", text: "State Bank of India" },
  { key: "EMAMILTD", text: "Emami Ltd." },
  { key: "BERGEPAINT", text: "Berger Paints India Ltd." },
  { key: "LT", text: "Larsen & Toubro Ltd." },
  { key: "HINDPETRO", text: "Hindustan Petroleum Corporation Ltd." },
  { key: "VOLTAS", text: "Voltas Ltd." },
  { key: "GODREJCP", text: "Godrej Consumer Products Ltd." },
  { key: "ABBOTINDIA", text: "Abbott India Ltd." },
  { key: "RECLTD", text: "REC Ltd." },
  { key: "SBICARD", text: "SBI Cards and Payment Services Ltd." },
  { key: "GODREJPROP", text: "Godrej Properties Ltd." },
  { key: "JSWSTEEL", text: "JSW Steel Ltd." },
  { key: "IOC", text: "Indian Oil Corporation Ltd." },
  { key: "PETRONET", text: "Petronet LNG Ltd." },
  { key: "FRETAIL", text: "Future Retail Ltd." },
  { key: "GRASIM", text: "Grasim Industries Ltd." },
  { key: "FEDERALBNK", text: "Federal Bank Ltd." },
  { key: "CANBK", text: "Canara Bank" },
  { key: "BBTC", text: "Bombay Burmah Trading Corporation Ltd." },
  { key: "TRENT", text: "Trent Ltd." },
  { key: "NESTLEIND", text: "Nestle India Ltd." },
  { key: "PIIND", text: "PI Industries Ltd." },
  { key: "MFSL", text: "Max Financial Services Ltd." },
  { key: "BHEL", text: "Bharat Heavy Electricals Ltd." },
  { key: "TATACHEM", text: "Tata Chemicals Ltd." },
  { key: "IDFCFIRSTB", text: "IDFC First Bank Ltd." },
  { key: "INDUSTOWER", text: "Indus Towers Ltd." },
  { key: "SUNPHARMA", text: "Sun Pharmaceutical Industries Ltd." },
  { key: "OIL", text: "Oil India Ltd." },
  { key: "TATAMOTORS", text: "Tata Motors Ltd." },
  { key: "BANKINDIA", text: "Bank of India" },
  { key: "CHOLAFIN", text: "Cholamandalam Investment and Finance Company Ltd." },
  { key: "MARUTI", text: "Maruti Suzuki India Ltd." },
  { key: "NAM-INDIA", text: "Nippon Life India Asset Management Ltd." },
  { key: "HDFC", text: "Housing Development Finance Corporation Ltd." },
  { key: "UBL", text: "United Breweries Ltd." },
  { key: "PAGEIND", text: "Page Industries Ltd." },
  { key: "HDFCAMC", text: "HDFC Asset Management Company Ltd." },
  { key: "INDHOTEL", text: "Indian Hotels Co. Ltd." },
  { key: "INDIGO", text: "InterGlobe Aviation Ltd." },
  { key: "BEL", text: "Bharat Electronics Ltd." },
  { key: "BPCL", text: "Bharat Petroleum Corporation Ltd." },
  { key: "MOTHERSUMI", text: "Motherson Sumi Systems Ltd." },
  { key: "COLPAL", text: "Colgate Palmolive (India) Ltd." },
  { key: "NAVINFLUOR", text: "Navin Fluorine International Ltd." },
  { key: "LTTS", text: "L&T Technology Services Ltd." },
  { key: "SANOFI", text: "Sanofi India Ltd." },
  { key: "BAJAJHLDNG", text: "Bajaj Holdings & Investment Ltd." },
  { key: "APLLTD", text: "Alembic Pharmaceuticals Ltd." },
  { key: "KOTAKBANK", text: "Kotak Mahindra Bank Ltd." },
  { key: "ABCAPITAL", text: "Aditya Birla Capital Ltd." },
  { key: "CADILAHC", text: "Cadila Healthcare Ltd." },
  { key: "MRF", text: "MRF Ltd." },
  { key: "M&M", text: "Mahindra & Mahindra Ltd." },
  { key: "PIDILITIND", text: "Pidilite Industries Ltd." },
  { key: "APOLLOTYRE", text: "Apollo Tyres Ltd." },
  { key: "AUBANK", text: "AU Small Finance Bank Ltd." },
  { key: "TCS", text: "Tata Consultancy Services Ltd." },
  { key: "FORTIS", text: "Fortis Healthcare Ltd." },
  { key: "NATCOPHARM", text: "NATCO Pharma Ltd." },
  { key: "AMARAJABAT", text: "Amara Raja Batteries Ltd." },
  { key: "EICHERMOT", text: "Eicher Motors Ltd." },
  { key: "DHANI", text: "Dhani Services Ltd." },
  { key: "SBILIFE", text: "SBI Life Insurance Company Ltd." },
  { key: "HCLTECH", text: "HCL Technologies Ltd." },
  { key: "SHREECEM", text: "Shree Cement Ltd." },
  { key: "UPL", text: "UPL Ltd." },
  { key: "ESCORTS", text: "Escorts Ltd." },
  { key: "DLF", text: "DLF Ltd." },
  { key: "BRITANNIA", text: "Britannia Industries Ltd." },
  { key: "MPHASIS", text: "MphasiS Ltd." },
  { key: "LUPIN", text: "Lupin Ltd." },
  { key: "TATAPOWER", text: "Tata Power Co. Ltd." },
  { key: "GSPL", text: "Gujarat State Petronet Ltd." },
  { key: "ONGC", text: "Oil & Natural Gas Corporation Ltd." },
  { key: "ISEC", text: "ICICI Securities Ltd." },
  { key: "EXIDEIND", text: "Exide Industries Ltd." },
  { key: "IRCTC", text: "Indian Railway Catering And Tourism Corporation Ltd." },
  { key: "NMDC", text: "NMDC Ltd." },
  { key: "ADANIENT", text: "Adani Enterprises Ltd." },
  { key: "IGL", text: "Indraprastha Gas Ltd." },
  { key: "GLENMARK", text: "Glenmark Pharmaceuticals Ltd." },
  { key: "WIPRO", text: "Wipro Ltd." },
  { key: "MARICO", text: "Marico Ltd." },
  { key: "COROMANDEL", text: "Coromandel International Ltd." },
  { key: "TORNTPHARM", text: "Torrent Pharmaceuticals Ltd." },
  { key: "ASHOKLEY", text: "Ashok Leyland Ltd." },
  { key: "ADANIGREEN", text: "Adani Green Energy Ltd." },
  { key: "OBEROIRLTY", text: "Oberoi Realty Ltd." },
  { key: "BIOCON", text: "Biocon Ltd." },
  { key: "HINDALCO", text: "Hindalco Industries Ltd." },
  { key: "SAIL", text: "Steel Authority of India Ltd." },
  { key: "RBLBANK", text: "RBL Bank Ltd." },
  { key: "MGL", text: "Mahanagar Gas Ltd." },
  { key: "GUJGASLTD", text: "Gujarat Gas Ltd." },
  { key: "LALPATHLAB", text: "Dr. Lal Path Labs Ltd." },
  { key: "NTPC", text: "NTPC Ltd." },
  { key: "BAJFINANCE", text: "Bajaj Finance Ltd." },
  { key: "ACC", text: "ACC Ltd." },
  { key: "POLYCAB", text: "Polycab India Ltd." },
  { key: "PFIZER", text: "Pfizer Ltd." },
  { key: "CONCOR", text: "Container Corporation of India Ltd." },
  { key: "AARTIIND", text: "Aarti Industries Ltd." },
  { key: "IDEA", text: "Vodafone Idea Ltd." },
  { key: "VBL", text: "Varun Beverages Ltd." },
  { key: "PEL", text: "Piramal Enterprises Ltd." },
  { key: "MUTHOOTFIN", text: "Muthoot Finance Ltd." },
  { key: "RELIANCE", text: "Reliance Industries Ltd." },
  { key: "OFSS", text: "Oracle Financial Services Software Ltd." },
  { key: "EDELWEISS", text: "Edelweiss Financial Services Ltd." },
  { key: "BHARATFORG", text: "Bharat Forge Ltd." },
  { key: "ADANIPORTS", text: "Adani Ports and Special Economic Zone Ltd." },
  { key: "DRREDDY", text: "Dr. Reddys Laboratories Ltd." },
  { key: "CROMPTON", text: "Crompton Greaves Consumer Electricals Ltd." },
  { key: "ASIANPAINT", text: "Asian Paints Ltd." },
  { key: "M&MFIN", text: "Mahindra and Mahindra Financial Services Ltd." },
  { key: "AJANTPHARM", text: "Ajanta Pharmaceuticals Ltd." },
  { key: "AXISBANK", text: "Axis Bank Ltd." },
  { key: "JSWENERGY", text: "JSW Energy Ltd." },
  { key: "IPCALAB", text: "Ipca Laboratories Ltd." },
  { key: "TORNTPOWER", text: "Torrent Power Ltd." },
  { key: "APOLLOHOSP", text: "Apollo Hospitals Enterprise Ltd." },
  { key: "SRF", text: "SRF Ltd." },
  { key: "BANKBARODA", text: "Bank of Baroda" },
  { key: "MCDOWELL-N", text: "United Spirits Ltd." },
  { key: "SRTRANSFIN", text: "Shriram Transport Finance Co. Ltd." },
  { key: "CUB", text: "City Union Bank Ltd." },
  { key: "LTI", text: "Larsen & Toubro Infotech Ltd." },
  { key: "PRESTIGE", text: "Prestige Estates Projects Ltd." },
  { key: "SYNGENE", text: "Syngene International Ltd." },
  { key: "WHIRLPOOL", text: "Whirlpool of India Ltd." },
  { key: "BATAINDIA", text: "Bata India Ltd." },
  { key: "HEROMOTOCO", text: "Hero MotoCorp Ltd." },
  { key: "ZEEL", text: "Zee Entertainment Enterprises Ltd." },
  { key: "AUROPHARMA", text: "Aurobindo Pharma Ltd." },
  { key: "HDFCBANK", text: "HDFC Bank Ltd." },
  { key: "NAUKRI", text: "Info Edge (India) Ltd." },
  { key: "ULTRACEMCO", text: "UltraTech Cement Ltd." },
  { key: "ITC", text: "ITC Ltd." },
  { key: "COFORGE", text: "Coforge Ltd." },
  { key: "HUDCO", text: "Housing & Urban Development Corporation Ltd." },
  { key: "GODREJAGRO", text: "Godrej Agrovet Ltd." },
  { key: "INFY", text: "Infosys Ltd." },
  { key: "MINDTREE", text: "MindTree Ltd." },
  { key: "BHARTIARTL", text: "Bharti Airtel Ltd." },
  { key: "TATASTEEL", text: "Tata Steel Ltd." },
  { key: "GODREJIND", text: "Godrej Industries Ltd." },
  { key: "AMBUJACEM", text: "Ambuja Cements Ltd." },
  { key: "SUNTV", text: "Sun TV Network Ltd." },
  { key: "POWERGRID", text: "Power Grid Corporation of India Ltd." },
  { key: "HDFCLIFE", text: "HDFC Life Insurance Company Ltd." },
  { key: "MANAPPURAM", text: "Manappuram Finance Ltd." },
  { key: "BALKRISIND", text: "Balkrishna Industries Ltd." },
  { key: "ABFRL", text: "Aditya Birla Fashion and Retail Ltd." },
  { key: "HINDZINC", text: "Hindustan Zinc Ltd." },
  { key: "CESC", text: "CESC Ltd." },
  { key: "RAJESHEXPO", text: "Rajesh Exports Ltd." },
  { key: "DALBHARAT", text: "Dalmia Bharat Ltd." },
  { key: "TITAN", text: "Titan Company Ltd." },
  { key: "DMART", text: "Avenue Supermarts Ltd." },
  { key: "TATACONSUM", text: "Tata Consumer Products Ltd." },
  { key: "CIPLA", text: "Cipla Ltd." },
  { key: "HAVELLS", text: "Havells India Ltd." },
  { key: "COALINDIA", text: "Coal India Ltd." },
  { key: "LICHSGFIN", text: "LIC Housing Finance Ltd." },
  { key: "JUBLFOOD", text: "Jubilant Foodworks Ltd." },
  { key: "BAJAJ-AUTO", text: "Bajaj Auto Ltd." },
  { key: "DABUR", text: "Dabur India Ltd." },
  { key: "CUMMINSIND", text: "Cummins India Ltd." },
  { key: "NATIONALUM", text: "National Aluminium Co. Ltd." },
  { key: "GICRE", text: "General Insurance Corporation of India" },
  { key: "ATGL", text: "Adani Total Gas Ltd." },
  { key: "BOSCHLTD", text: "Bosch Ltd." },
  { key: "BAJAJFINSV", text: "Bajaj Finserv Ltd." },
  { key: "TECHM", text: "Tech Mahindra Ltd." },
  { key: "ADANITRANS", text: "Adani Transmission Ltd." },
  { key: "CASTROLIND", text: "Castrol India Ltd." },
  { key: "PFC", text: "Power Finance Corporation Ltd." },
  { key: "ICICIPRULI", text: "ICICI Prudential Life Insurance Company Ltd." },
  { key: "BANDHANBNK", text: "Bandhan Bank Ltd." },
  { key: "YESBANK", text: "Yes Bank Ltd." },
  { key: "ALKEM", text: "Alkem Laboratories Ltd." },
  { key: "INDUSINDBK", text: "IndusInd Bank Ltd." },
  { key: "SIEMENS", text: "Siemens Ltd." },
  { key: "TVSMOTOR", text: "TVS Motor Company Ltd." },
  { key: "IBULHSGFIN", text: "Indiabulls Housing Finance Ltd." },
  { key: "PNB", text: "Punjab National Bank" },
  { key: "VGUARD", text: "V-Guard Industries Ltd." },
];

export let CANDLE_TYPE_LIST = [
  { key: "5m", text: "5min" },
  { key: "15m", text: "15 min" },
  { key: "1h", text: "1 hour" },
  { key: "1d", text: "1d" },
];

export let DURATION_TYPE_LIST = [
  { key: "90", text: "3 months" },
  { key: "180", text: "6 months" },
  { key: "365", text: "1 years" },
  { key: "730", text: "2 years" },
];

export let INDICATOR_LIST = [
  { key: "--", text: "Select" },
  { key: "close", text: "Close Of" },
  { key: "open", text: "Open Of" },
  { key: "high", text: "High of" },
  { key: "low", text: "Low of " },
  { key: "number", text: "Number" },
  { key: "volume", text: "Volume of" },
  { key: "ema_5", text: "ema_5" },
  { key: "ema_8", text: "ema_8" },
  { key: "ema_13", text: "ema_13" },
  { key: "ema_20", text: "ema_20" },
  { key: "ema_28", text: "ema_28" },
  { key: "ema_50", text: "ema_500" },
  { key: "ema_100", text: "ema_100" },
  { key: "ema_200", text: "ema_200" },
  { key: "rsi_6", text: "rsi_6" },
  { key: "rsi_12", text: "rsi_12" },
  { key: "rsi_14", text: "rsi_14" },
  { key: "rsi_18", text: "rsi_18" },
  { key: "macd_line", text: "macd_macd" },
  { key: "macd_control", text: "macd_control" },
  { key: "sar", text: "P. Sar" },
];

export let OFFSET_LIST = [
  { key: "--", text: "Select" },
  { key: "1d:0", text: "[0]Day" },
  { key: "1d:-1", text: "[-1]Day" },
  { key: "1d:-2", text: "[-2]Day" },
  { key: "1d:-3", text: "[-3]Day" },
  { key: "1d:-4", text: "[-4]Day" },
  { key: "1d:-5", text: "[-5]Day" },
  { key: "5m:0", text: "[0]5m" },
  { key: "5m:-1", text: "[-1]5m" },
  { key: "5m:-2", text: "[-2]5m" },
  { key: "5m:-3", text: "[-3]5m" },
  { key: "5m:-4", text: "[-4]5m" },
  { key: "5m:-5", text: "[-5]5m" },
  { key: "15m:0", text: "[0]15m" },
  { key: "15m:-1", text: "[-1]15m" },
  { key: "15m:-2", text: "[-2]15m" },
  { key: "15m:-3", text: "[-3]15m" },
  { key: "15m:-4", text: "[-4]15m" },
  { key: "15m:-5", text: "[-5]15m" },
  { key: "1h:0", text: "[0]1h" },
  { key: "1h:-1", text: "[-1]1h" },
  { key: "1h:-2", text: "[-2]1h" },
  { key: "1h:-3", text: "[-3]1h" },
  { key: "1h:-4", text: "[-4]1h" },
  { key: "1h:-5", text: "[-5]1h" },
];

export let OPERATOR_LIST = [
  { key: "--", text: "Select" },
  { key: "==", text: "Equals to" },
  { key: "!=", text: "Not equals to" },
  { key: ">", text: "Greater than" },
  { key: "<", text: "Less then" },
  { key: ">=", text: "Greater or equal" },
  { key: "<=", text: "Lesser or equal " },
  { key: "+", text: "Plus" },
  { key: "-", text: "Minus" },
  { key: "*", text: "Multiply" },
  { key: "/", text: "Divide" },
];

export let SCREEN_COLUMNS_LIST = [
  { key: "indicator:1d:0:close", text: "Latest close" },
  { key: "indicator:1d:-1:close", text: "Prev Day close" },
  { key: "indicator:1d:0:volume", text: "Latest Volume" },
  { key: "indicator:1d:0:rsi_14", text: "Lastest RSI(14)" },
  { key: "indicator:1d:0:close_change", text: "Price Change %" },
  { key: "indicator:1d:0:volume_change", text: "volume_change%" },
  { key: "indicator:1d:0:high_low_gap", text: "high_low_gap " },
  { key: "indicator:1d:0:high_low_gap_percentage", text: "high_low_gap_percentage" },
];
