export const NIFTY_200 = [
  { key: "^NSEI", text: "NIFTY_50" },
  { key: "^NSEBANK", text: "NYFTY_BANK" },
  { key: "^CNXIT", text: "NIFTY IT" },
  { key: "DIVISLAB.NS", text: "Divis Laboratories Ltd." },
  { key: "JINDALSTEL.NS", text: "Jindal Steel & Power Ltd." },
  { key: "ENDURANCE.NS", text: "Endurance Technologies Ltd." },
  { key: "PGHH.NS", text: "Procter & Gamble Hygiene & Health Care Ltd." },
  { key: "GMRINFRA.NS", text: "GMR Infrastructure Ltd." },
  { key: "UNIONBANK.NS", text: "Union Bank of India" },
  { key: "RAMCOCEM.NS", text: "The Ramco Cements Ltd." },
  { key: "GAIL.NS", text: "GAIL (India) Ltd." },
  { key: "ICICIBANK.NS", text: "ICICI Bank Ltd." },
  { key: "ICICIGI.NS", text: "ICICI Lombard General Insurance Company Ltd." },
  { key: "LTFH.NS", text: "L&T Finance Holdings Ltd." },
  { key: "HINDUNILVR.NS", text: "Hindustan Unilever Ltd." },
  { key: "SBIN.NS", text: "State Bank of India" },
  { key: "EMAMILTD.NS", text: "Emami Ltd." },
  { key: "BERGEPAINT.NS", text: "Berger Paints India Ltd." },
  { key: "LT.NS", text: "Larsen & Toubro Ltd." },
  { key: "HINDPETRO.NS", text: "Hindustan Petroleum Corporation Ltd." },
  { key: "VOLTAS.NS", text: "Voltas Ltd." },
  { key: "GODREJCP.NS", text: "Godrej Consumer Products Ltd." },
  { key: "ABBOTINDIA.NS", text: "Abbott India Ltd." },
  { key: "RECLTD.NS", text: "REC Ltd." },
  { key: "SBICARD.NS", text: "SBI Cards and Payment Services Ltd." },
  { key: "GODREJPROP.NS", text: "Godrej Properties Ltd." },
  { key: "JSWSTEEL.NS", text: "JSW Steel Ltd." },
  { key: "IOC.NS", text: "Indian Oil Corporation Ltd." },
  { key: "PETRONET.NS", text: "Petronet LNG Ltd." },
  { key: "FRETAIL.NS", text: "Future Retail Ltd." },
  { key: "GRASIM.NS", text: "Grasim Industries Ltd." },
  { key: "FEDERALBNK.NS", text: "Federal Bank Ltd." },
  { key: "CANBK.NS", text: "Canara Bank" },
  { key: "BBTC.NS", text: "Bombay Burmah Trading Corporation Ltd." },
  { key: "TRENT.NS", text: "Trent Ltd." },
  { key: "NESTLEIND.NS", text: "Nestle India Ltd." },
  { key: "PIIND.NS", text: "PI Industries Ltd." },
  { key: "MFSL.NS", text: "Max Financial Services Ltd." },
  { key: "BHEL.NS", text: "Bharat Heavy Electricals Ltd." },
  { key: "TATACHEM.NS", text: "Tata Chemicals Ltd." },
  { key: "IDFCFIRSTB.NS", text: "IDFC First Bank Ltd." },
  { key: "INDUSTOWER.NS", text: "Indus Towers Ltd." },
  { key: "SUNPHARMA.NS", text: "Sun Pharmaceutical Industries Ltd." },
  { key: "OIL.NS", text: "Oil India Ltd." },
  { key: "TATAMOTORS.NS", text: "Tata Motors Ltd." },
  { key: "BANKINDIA.NS", text: "Bank of India" },
  { key: "CHOLAFIN.NS", text: "Cholamandalam Investment and Finance Company Ltd." },
  { key: "MARUTI.NS", text: "Maruti Suzuki India Ltd." },
  { key: "NAM-INDIA.NS", text: "Nippon Life India Asset Management Ltd." },
  { key: "HDFC.NS", text: "Housing Development Finance Corporation Ltd." },
  { key: "UBL.NS", text: "United Breweries Ltd." },
  { key: "PAGEIND.NS", text: "Page Industries Ltd." },
  { key: "HDFCAMC.NS", text: "HDFC Asset Management Company Ltd." },
  { key: "INDHOTEL.NS", text: "Indian Hotels Co. Ltd." },
  { key: "INDIGO.NS", text: "InterGlobe Aviation Ltd." },
  { key: "BEL.NS", text: "Bharat Electronics Ltd." },
  { key: "BPCL.NS", text: "Bharat Petroleum Corporation Ltd." },
  { key: "MOTHERSUMI.NS", text: "Motherson Sumi Systems Ltd." },
  { key: "COLPAL.NS", text: "Colgate Palmolive (India) Ltd." },
  { key: "NAVINFLUOR.NS", text: "Navin Fluorine International Ltd." },
  { key: "LTTS.NS", text: "L&T Technology Services Ltd." },
  { key: "SANOFI.NS", text: "Sanofi India Ltd." },
  { key: "BAJAJHLDNG.NS", text: "Bajaj Holdings & Investment Ltd." },
  { key: "APLLTD.NS", text: "Alembic Pharmaceuticals Ltd." },
  { key: "KOTAKBANK.NS", text: "Kotak Mahindra Bank Ltd." },
  { key: "ABCAPITAL.NS", text: "Aditya Birla Capital Ltd." },
  { key: "CADILAHC.NS", text: "Cadila Healthcare Ltd." },
  { key: "MRF.NS", text: "MRF Ltd." },
  { key: "M&M.NS", text: "Mahindra & Mahindra Ltd." },
  { key: "PIDILITIND.NS", text: "Pidilite Industries Ltd." },
  { key: "APOLLOTYRE.NS", text: "Apollo Tyres Ltd." },
  { key: "AUBANK.NS", text: "AU Small Finance Bank Ltd." },
  { key: "TCS.NS", text: "Tata Consultancy Services Ltd." },
  { key: "FORTIS.NS", text: "Fortis Healthcare Ltd." },
  { key: "NATCOPHARM.NS", text: "NATCO Pharma Ltd." },
  { key: "AMARAJABAT.NS", text: "Amara Raja Batteries Ltd." },
  { key: "EICHERMOT.NS", text: "Eicher Motors Ltd." },
  { key: "DHANI.NS", text: "Dhani Services Ltd." },
  { key: "SBILIFE.NS", text: "SBI Life Insurance Company Ltd." },
  { key: "HCLTECH.NS", text: "HCL Technologies Ltd." },
  { key: "SHREECEM.NS", text: "Shree Cement Ltd." },
  { key: "UPL.NS", text: "UPL Ltd." },
  { key: "ESCORTS.NS", text: "Escorts Ltd." },
  { key: "DLF.NS", text: "DLF Ltd." },
  { key: "BRITANNIA.NS", text: "Britannia Industries Ltd." },
  { key: "MPHASIS.NS", text: "MphasiS Ltd." },
  { key: "LUPIN.NS", text: "Lupin Ltd." },
  { key: "TATAPOWER.NS", text: "Tata Power Co. Ltd." },
  { key: "GSPL.NS", text: "Gujarat State Petronet Ltd." },
  { key: "ONGC.NS", text: "Oil & Natural Gas Corporation Ltd." },
  { key: "ISEC.NS", text: "ICICI Securities Ltd." },
  { key: "EXIDEIND.NS", text: "Exide Industries Ltd." },
  { key: "IRCTC.NS", text: "Indian Railway Catering And Tourism Corporation Ltd." },
  { key: "NMDC.NS", text: "NMDC Ltd." },
  { key: "ADANIENT.NS", text: "Adani Enterprises Ltd." },
  { key: "IGL.NS", text: "Indraprastha Gas Ltd." },
  { key: "GLENMARK.NS", text: "Glenmark Pharmaceuticals Ltd." },
  { key: "WIPRO.NS", text: "Wipro Ltd." },
  { key: "MARICO.NS", text: "Marico Ltd." },
  { key: "COROMANDEL.NS", text: "Coromandel International Ltd." },
  { key: "TORNTPHARM.NS", text: "Torrent Pharmaceuticals Ltd." },
  { key: "ASHOKLEY.NS", text: "Ashok Leyland Ltd." },
  { key: "ADANIGREEN.NS", text: "Adani Green Energy Ltd." },
  { key: "OBEROIRLTY.NS", text: "Oberoi Realty Ltd." },
  { key: "BIOCON.NS", text: "Biocon Ltd." },
  { key: "HINDALCO.NS", text: "Hindalco Industries Ltd." },
  { key: "SAIL.NS", text: "Steel Authority of India Ltd." },
  { key: "RBLBANK.NS", text: "RBL Bank Ltd." },
  { key: "MGL.NS", text: "Mahanagar Gas Ltd." },
  { key: "GUJGASLTD.NS", text: "Gujarat Gas Ltd." },
  { key: "LALPATHLAB.NS", text: "Dr. Lal Path Labs Ltd." },
  { key: "NTPC.NS", text: "NTPC Ltd." },
  { key: "BAJFINANCE.NS", text: "Bajaj Finance Ltd." },
  { key: "ACC.NS", text: "ACC Ltd." },
  { key: "POLYCAB.NS", text: "Polycab India Ltd." },
  { key: "PFIZER.NS", text: "Pfizer Ltd." },
  { key: "CONCOR.NS", text: "Container Corporation of India Ltd." },
  { key: "AARTIIND.NS", text: "Aarti Industries Ltd." },
  { key: "IDEA.NS", text: "Vodafone Idea Ltd." },
  { key: "VBL.NS", text: "Varun Beverages Ltd." },
  { key: "PEL.NS", text: "Piramal Enterprises Ltd." },
  { key: "MUTHOOTFIN.NS", text: "Muthoot Finance Ltd." },
  { key: "RELIANCE.NS", text: "Reliance Industries Ltd." },
  { key: "OFSS.NS", text: "Oracle Financial Services Software Ltd." },
  { key: "EDELWEISS.NS", text: "Edelweiss Financial Services Ltd." },
  { key: "BHARATFORG.NS", text: "Bharat Forge Ltd." },
  { key: "ADANIPORTS.NS", text: "Adani Ports and Special Economic Zone Ltd." },
  { key: "DRREDDY.NS", text: "Dr. Reddys Laboratories Ltd." },
  { key: "CROMPTON.NS", text: "Crompton Greaves Consumer Electricals Ltd." },
  { key: "ASIANPAINT.NS", text: "Asian Paints Ltd." },
  { key: "M&MFIN.NS", text: "Mahindra and Mahindra Financial Services Ltd." },
  { key: "AJANTPHARM.NS", text: "Ajanta Pharmaceuticals Ltd." },
  { key: "AXISBANK.NS", text: "Axis Bank Ltd." },
  { key: "JSWENERGY.NS", text: "JSW Energy Ltd." },
  { key: "IPCALAB.NS", text: "Ipca Laboratories Ltd." },
  { key: "TORNTPOWER.NS", text: "Torrent Power Ltd." },
  { key: "APOLLOHOSP.NS", text: "Apollo Hospitals Enterprise Ltd." },
  { key: "SRF.NS", text: "SRF Ltd." },
  { key: "BANKBARODA.NS", text: "Bank of Baroda" },
  { key: "MCDOWELL-N.NS", text: "United Spirits Ltd." },
  { key: "SRTRANSFIN.NS", text: "Shriram Transport Finance Co. Ltd." },
  { key: "CUB.NS", text: "City Union Bank Ltd." },
  { key: "LTI.NS", text: "Larsen & Toubro Infotech Ltd." },
  { key: "PRESTIGE.NS", text: "Prestige Estates Projects Ltd." },
  { key: "SYNGENE.NS", text: "Syngene International Ltd." },
  { key: "WHIRLPOOL.NS", text: "Whirlpool of India Ltd." },
  { key: "BATAINDIA.NS", text: "Bata India Ltd." },
  { key: "HEROMOTOCO.NS", text: "Hero MotoCorp Ltd." },
  { key: "ZEEL.NS", text: "Zee Entertainment Enterprises Ltd." },
  { key: "AUROPHARMA.NS", text: "Aurobindo Pharma Ltd." },
  { key: "HDFCBANK.NS", text: "HDFC Bank Ltd." },
  { key: "NAUKRI.NS", text: "Info Edge (India) Ltd." },
  { key: "ULTRACEMCO.NS", text: "UltraTech Cement Ltd." },
  { key: "ITC.NS", text: "ITC Ltd." },
  { key: "COFORGE.NS", text: "Coforge Ltd." },
  { key: "HUDCO.NS", text: "Housing & Urban Development Corporation Ltd." },
  { key: "GODREJAGRO.NS", text: "Godrej Agrovet Ltd." },
  { key: "INFY.NS", text: "Infosys Ltd." },
  { key: "MINDTREE.NS", text: "MindTree Ltd." },
  { key: "BHARTIARTL.NS", text: "Bharti Airtel Ltd." },
  { key: "TATASTEEL.NS", text: "Tata Steel Ltd." },
  { key: "GODREJIND.NS", text: "Godrej Industries Ltd." },
  { key: "AMBUJACEM.NS", text: "Ambuja Cements Ltd." },
  { key: "SUNTV.NS", text: "Sun TV Network Ltd." },
  { key: "POWERGRID.NS", text: "Power Grid Corporation of India Ltd." },
  { key: "HDFCLIFE.NS", text: "HDFC Life Insurance Company Ltd." },
  { key: "MANAPPURAM.NS", text: "Manappuram Finance Ltd." },
  { key: "BALKRISIND.NS", text: "Balkrishna Industries Ltd." },
  { key: "ABFRL.NS", text: "Aditya Birla Fashion and Retail Ltd." },
  { key: "HINDZINC.NS", text: "Hindustan Zinc Ltd." },
  { key: "CESC.NS", text: "CESC Ltd." },
  { key: "RAJESHEXPO.NS", text: "Rajesh Exports Ltd." },
  { key: "DALBHARAT.NS", text: "Dalmia Bharat Ltd." },
  { key: "TITAN.NS", text: "Titan Company Ltd." },
  { key: "DMART.NS", text: "Avenue Supermarts Ltd." },
  { key: "TATACONSUM.NS", text: "Tata Consumer Products Ltd." },
  { key: "CIPLA.NS", text: "Cipla Ltd." },
  { key: "HAVELLS.NS", text: "Havells India Ltd." },
  { key: "COALINDIA.NS", text: "Coal India Ltd." },
  { key: "LICHSGFIN.NS", text: "LIC Housing Finance Ltd." },
  { key: "JUBLFOOD.NS", text: "Jubilant Foodworks Ltd." },
  { key: "BAJAJ-AUTO.NS", text: "Bajaj Auto Ltd." },
  { key: "DABUR.NS", text: "Dabur India Ltd." },
  { key: "CUMMINSIND.NS", text: "Cummins India Ltd." },
  { key: "NATIONALUM.NS", text: "National Aluminium Co. Ltd." },
  { key: "GICRE.NS", text: "General Insurance Corporation of India" },
  { key: "ATGL.NS", text: "Adani Total Gas Ltd." },
  { key: "BOSCHLTD.NS", text: "Bosch Ltd." },
  { key: "BAJAJFINSV.NS", text: "Bajaj Finserv Ltd." },
  { key: "TECHM.NS", text: "Tech Mahindra Ltd." },
  { key: "ADANITRANS.NS", text: "Adani Transmission Ltd." },
  { key: "CASTROLIND.NS", text: "Castrol India Ltd." },
  { key: "PFC.NS", text: "Power Finance Corporation Ltd." },
  { key: "ICICIPRULI.NS", text: "ICICI Prudential Life Insurance Company Ltd." },
  { key: "BANDHANBNK.NS", text: "Bandhan Bank Ltd." },
  { key: "YESBANK.NS", text: "Yes Bank Ltd." },
  { key: "ALKEM.NS", text: "Alkem Laboratories Ltd." },
  { key: "INDUSINDBK.NS", text: "IndusInd Bank Ltd." },
  { key: "SIEMENS.NS", text: "Siemens Ltd." },
  { key: "TVSMOTOR.NS", text: "TVS Motor Company Ltd." },
  { key: "IBULHSGFIN.NS", text: "Indiabulls Housing Finance Ltd." },
  { key: "PNB.NS", text: "Punjab National Bank" },
  { key: "VGUARD.NS", text: "V-Guard Industries Ltd." },
];

export let CANDLE_TYPE_LIST = [
  { key: "5m", text: "5min" },
  { key: "15m", text: "15 min" },
  { key: "1h", text: "1 hour" },
  { key: "1d", text: "1d" },
];

export let DURATION_TYPE_LIST = [
  { key: "90", text: "3 months" },
  { key: "180", text: "6 months" },
  { key: "365", text: "1 years" },
  { key: "730", text: "2 years" },
];

export let SHORT_CANDLE_DURATION = [
  { key: "30", text: "30" },
  { key: "60", text: "60" },
  { key: "90", text: "90" },
  { key: "180", text: "180" },
];

export let INDICATOR_LIST = [
  { key: "close", text: "Close" },
  { key: "open", text: "Open" },
  { key: "high", text: "High" },
  { key: "low", text: "Low" },
  { key: "number", text: "Number" },
  { key: "volume", text: "Volume" },
  { key: "ema_5", text: "ema_5" },
  { key: "ema_8", text: "ema_8" },
  { key: "ema_13", text: "ema_13" },
  { key: "ema_20", text: "ema_20" },
  { key: "ema_28", text: "ema_28" },
  { key: "ema_50", text: "ema_500" },
  { key: "ema_100", text: "ema_100" },
  { key: "ema_200", text: "ema_200" },
  { key: "rsi_6", text: "rsi_6" },
  { key: "rsi_12", text: "rsi_12" },
  { key: "rsi_14", text: "rsi_14" },
  { key: "rsi_18", text: "rsi_18" },
  { key: "macd_line", text: "macd_macd" },
  { key: "macd_control", text: "macd_control" },
  { key: "sar", text: "P. Sar" },
  { key: "candle", text: "Candle" },
];

export let OFFSET_LIST = [
  { key: "--", text: "Select" },
  { key: "1d:0", text: "[0]Day" },
  { key: "1d:-1", text: "[-1]Day" },
  { key: "1d:-2", text: "[-2]Day" },
  { key: "1d:-3", text: "[-3]Day" },
  { key: "1d:-4", text: "[-4]Day" },
  { key: "1d:-5", text: "[-5]Day" },
  { key: "5m:0", text: "[0]5m" },
  { key: "5m:-1", text: "[-1]5m" },
  { key: "5m:-2", text: "[-2]5m" },
  { key: "5m:-3", text: "[-3]5m" },
  { key: "5m:-4", text: "[-4]5m" },
  { key: "5m:-5", text: "[-5]5m" },
  { key: "15m:0", text: "[0]15m" },
  { key: "15m:-1", text: "[-1]15m" },
  { key: "15m:-2", text: "[-2]15m" },
  { key: "15m:-3", text: "[-3]15m" },
  { key: "15m:-4", text: "[-4]15m" },
  { key: "15m:-5", text: "[-5]15m" },
  { key: "1h:0", text: "[0]1h" },
  { key: "1h:-1", text: "[-1]1h" },
  { key: "1h:-2", text: "[-2]1h" },
  { key: "1h:-3", text: "[-3]1h" },
  { key: "1h:-4", text: "[-4]1h" },
  { key: "1h:-5", text: "[-5]1h" },
];

export let OPERATOR_LIST = [
  { key: "--", text: "Select" },
  { key: "==", text: "Equals to" },
  { key: "!=", text: "Not equals to" },
  { key: ">", text: "Greater than" },
  { key: "<", text: "Less then" },
  { key: ">=", text: "Greater or equal" },
  { key: "<=", text: "Lesser or equal " },
  { key: "+", text: "Plus" },
  { key: "-", text: "Minus" },
  { key: "*", text: "Multiply" },
  { key: "/", text: "Divide" },
];
export let COMMON_COLUMNS_LIST = [
  { key: "symbol", text: "symbol" },
  { key: "close", text: "close" },
  { key: "change", text: "change" },
];

export let SCREEN_COLUMNS_LIST: Array<any> = COMMON_COLUMNS_LIST;
for (let z of INDICATOR_LIST) {
  for (let x of CANDLE_TYPE_LIST) {
    for (let y = 0; y >= -1; y--) {
      SCREEN_COLUMNS_LIST.push({ key: `indicator:${x.key}:${y}:${z.key}`, text: `${x.key} [${y}] ${z.text}` });
    }
  }
}

export let LATEST_SCREEN_COLUMNS_LIST: Array<any> = COMMON_COLUMNS_LIST;
for (let z of INDICATOR_LIST) {
  for (let x of CANDLE_TYPE_LIST) {
    for (let y = 0; y >= 0; y--) {
      LATEST_SCREEN_COLUMNS_LIST.push({ key: `indicator:${x.key}:${y}:${z.key}`, text: `${x.key} ${z.text}` });
    }
  }
}

export let DEFAULT_FOCUS_GROUP = [
  {
    _id: "default",
    name: "Default Group",
    list: ["^NSEI", "WIPRO.NS", "DRREDDY.NS", "BAJAJ-AUTO.NS", "BHARTIARTL.NS", "BRITANNIA.NS", "GODREJCP.NS", "NAUKRI.NS"],
  },
  {
    _id: "default2",
    name: "Default Group 2",
    list: ["GODREJCP.NS", "NAUKRI.NS"],
  },
];
export let CHART_DISPLAY_CONFIG = [
  { key: "candle", text: "candle" },
  { key: "volume", text: "volume" },
];
